### ISSUE TITLE
slack integration

### ISSUE THREAD

**Issue by koheisg** [fi1446/perfect_rails#5]
githubの設定でownerでないとできない設定なのでお願いしたいです。

ブラウザでslackのforwardチームにログインしてもらって、
# kame_study にこのリポジトリのcommitやコメントを連携させてほしいです。

参考URL
http://ryouzis.hatenablog.com/entry/2015/08/14/190349

**Comment by t19106** [comment]
なるほど、勉強ログは杉さんがやってくれたってだけで、こっちはレポジトリ作った本人が設定しないとダメなんですね。
設定DONEです。
